### ISSUE TITLE
Implementera savefile lokalt

### ISSUE THREAD

**Issue by Alphapork** [Ryllee/TypingHeroLayout#8]

**Comment by Alphapork** [comment]
Username
I pointHandler: points, totalpoints, pointsperletter, pointspersec.
I uppdatering: cost, currentlevel.

**Comment by Ryllee** [comment]
Fungerar till större del, kan ej spara info om uppgraderingar.

**Comment by Ryllee** [comment]
Nu fungerade som den ska i detta skede
